/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package aero.developer.beacons.beaconglass;

public final class R {
    public static final class anim {
        public static final int hide_contextual=0x7f040000;
        public static final int show_contextual=0x7f040001;
    }
    public static final class attr {
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int activity_horizontal_margin=0x7f070005;
        public static final int activity_vertical_margin=0x7f070006;
        public static final int background_dim_amount=0x7f070004;
        public static final int card_margin=0x7f070007;
        public static final int large_text_size=0x7f070001;
        public static final int medium_text_size=0x7f070002;
        public static final int slider_bar_height=0x7f070000;
        public static final int small_text_size=0x7f070003;
        public static final int tip_margin_bottom=0x7f070008;
    }
    public static final class drawable {
        public static final int bar_candy0001=0x7f020000;
        public static final int bar_candy0002=0x7f020001;
        public static final int bar_candy0003=0x7f020002;
        public static final int bar_candy0004=0x7f020003;
        public static final int bar_candy0005=0x7f020004;
        public static final int bar_candy0006=0x7f020005;
        public static final int bar_candy0007=0x7f020006;
        public static final int bar_candy0008=0x7f020007;
        public static final int bar_candy0009=0x7f020008;
        public static final int bar_candy0010=0x7f020009;
        public static final int bar_candy0011=0x7f02000a;
        public static final int bar_candy0012=0x7f02000b;
        public static final int bar_candy0013=0x7f02000c;
        public static final int bar_candy0014=0x7f02000d;
        public static final int bar_candy0015=0x7f02000e;
        public static final int bar_candy0016=0x7f02000f;
        public static final int bar_candy0017=0x7f020010;
        public static final int bar_candy0018=0x7f020011;
        public static final int bar_candy0019=0x7f020012;
        public static final int bar_candy0020=0x7f020013;
        public static final int bar_candy0021=0x7f020014;
        public static final int bar_candy0022=0x7f020015;
        public static final int bar_candy0023=0x7f020016;
        public static final int bar_candy0024=0x7f020017;
        public static final int bar_candy0025=0x7f020018;
        public static final int bar_candy0026=0x7f020019;
        public static final int bar_candy0027=0x7f02001a;
        public static final int bar_candy0028=0x7f02001b;
        public static final int bar_candy0029=0x7f02001c;
        public static final int bar_candy0030=0x7f02001d;
        public static final int ic_launcher=0x7f02001e;
        public static final int slider_indeterminate=0x7f02001f;
    }
    public static final class id {
        public static final int action_settings=0x7f080009;
        public static final int icon=0x7f080005;
        public static final int indeterminate_slider=0x7f080001;
        public static final int label=0x7f080006;
        public static final int loading=0x7f080002;
        public static final int ms_dialog=0x7f080004;
        public static final int msgView=0x7f080003;
        public static final int secondary_label=0x7f080007;
        public static final int slider=0x7f080008;
        public static final int slider_control=0x7f080000;
    }
    public static final class integer {
        public static final int activity_animation_duration_ms=0x7f090000;
        public static final int api_TIME_OUT=0x7f090007;
        public static final int horizontal_scroll_deferred_load_animation_duration_ms=0x7f090003;
        public static final int horizontal_scroll_deferred_sizing_animation_duration_ms=0x7f090004;
        public static final int infos_error_duration_ms=0x7f090001;
        public static final int infos_success_duration_ms=0x7f090002;
        public static final int sys_storage_threshold_bytes=0x7f090006;
        public static final int sys_storage_threshold_percentage=0x7f090005;
    }
    public static final class layout {
        public static final int activity_load=0x7f030000;
        public static final int main=0x7f030001;
        public static final int message_dialog=0x7f030002;
        public static final int message_dialog_expanded=0x7f030003;
        public static final int slider=0x7f030004;
    }
    public static final class menu {
        public static final int main=0x7f0c0000;
    }
    public static final class raw {
        public static final int airlinecodes=0x7f060000;
        public static final int airports=0x7f060001;
        public static final int sound_dismiss=0x7f060002;
        public static final int sound_error=0x7f060003;
        public static final int sound_success=0x7f060004;
    }
    public static final class string {
        public static final int AirportURL=0x7f0b0002;
        public static final int Beacon=0x7f0b0009;
        public static final int BeaconDetails=0x7f0b0004;
        public static final int RanginInterval=0x7f0b0006;
        public static final int TrackingBeacon=0x7f0b000a;
        public static final int action_settings=0x7f0b0008;
        public static final int api_KEY_NAME=0x7f0b0000;
        public static final int api_KEY_VALUE=0x7f0b0001;
        public static final int appId=0x7f0b0005;
        public static final int app_name=0x7f0b0007;
        public static final int beaconsUrl=0x7f0b0003;
        public static final int ble_not_supported=0x7f0b000f;
        public static final int cancel=0x7f0b000c;
        public static final int dismiss=0x7f0b000b;
        public static final int error_bluetooth_not_supported=0x7f0b0010;
        public static final int loading_beacon=0x7f0b000d;
        public static final int noDescriptive=0x7f0b000e;
    }
    public static final class style {
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f0a0007;
        public static final int ContextualDialog=0x7f0a0004;
        public static final int ContextualDialogTheme=0x7f0a0005;
        public static final int ContextualDialogTheme_NoAnimation=0x7f0a0006;
        /**  <item name="android:shadowDx">1.0</item>
        <item name="android:shadowDy">1.0</item>
        <item name="android:shadowRadius">1.0</item> 
         */
        public static final int LargeOverlayText=0x7f0a0001;
        public static final int MediumOverlayText=0x7f0a0002;
        public static final int OverlayText=0x7f0a0000;
        public static final int SmallOverlayText=0x7f0a0003;
    }
    public static final class xml {
        public static final int voice_trigger=0x7f050000;
    }
}
